version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy

permissions:
  - object: /home/ubuntu/deploy/
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /start_server.sh
      timeout: 60
      runas: ubuntu